### ISSUE TITLE
[Bug]: Error: Process completed with exit code 255.

### ISSUE THREAD

**Issue by ll7** [una-auxme/paf23#203]
### Current Behavior

```
paf22-test-agent-1            | Skipping scenario 'OppositeVehicleTakingPriority_4' due to setup error: time-out of 300000ms while waiting for the simulator, make sure the simulator is ready and connected to carla-simulator:2000
paf22-test-agent-1            | 
paf22-test-agent-1            | Traceback (most recent call last):
paf22-test-agent-1            |   File "/opt/leaderboard-py3/leaderboard/scenarios/route_scenario.py", line 321, in build_scenarios
paf22-test-agent-1            |     scenario_instance = scenario_class(self.world, [ego_vehicle], scenario_config, timeout=self.timeout)
paf22-test-agent-1            |   File "/opt/scenario_runner/srunner/scenarios/opposite_vehicle_taking_priority.py", line 267, in __init__
paf22-test-agent-1            |     super().__init__(world, ego_vehicles, config, randomize, debug_mode, criteria_enable, timeout)
paf22-test-agent-1            |   File "/opt/scenario_runner/srunner/scenarios/opposite_vehicle_taking_priority.py", line 70, in __init__
paf22-test-agent-1            |     super().__init__("OppositeVehicleJunction",
paf22-test-agent-1            |   File "/opt/leaderboard-py3/srunner/scenarios/basic_scenario.py", line 64, in __init__
paf22-test-agent-1            |     self._initialize_actors(config)
paf22-test-agent-1            |   File "/opt/scenario_runner/srunner/scenarios/opposite_vehicle_taking_priority.py", line 122, in _initialize_actors
paf22-test-agent-1            |     opposite_actor = CarlaDataProvider.request_new_actor(
paf22-test-agent-1            |   File "/opt/leaderboard-py3/srunner/scenariomanager/carla_data_provider.py", line 625, in request_new_actor
paf22-test-agent-1            |     CarlaDataProvider._world.wait_for_tick()
paf22-test-agent-1            | RuntimeError: time-out of 300000ms while waiting for the simulator, make sure the simulator is ready and connected to carla-simulator:2000
paf22-test-agent-1            | 
paf22-test-agent-1            | > Registering the route statistics
paf22-test-agent-1            | WARNING: attempting to unsubscribe from stream but sensor wasn't listening: Actor 7735 (sensor.other.imu) 
paf22-test-agent-1            | ERROR: failed to destroy actor 7735 : unable to destroy actor: not found 
paf22-test-agent-1            | WARNING: attempting to unsubscribe from stream but sensor wasn't listening: Actor 7734 (sensor.other.gnss) 
paf22-test-agent-1            | ERROR: failed to destroy actor 7734 : unable to destroy actor: not found 
paf22-test-agent-1            | WARNING: attempting to unsubscribe from stream but sensor wasn't listening: Actor 7733 (sensor.other.radar) 
paf22-test-agent-1            | ERROR: failed to destroy actor 7733 : unable to destroy actor: not found 
paf22-test-agent-1            | WARNING: attempting to unsubscribe from stream but sensor wasn't listening: Actor 7732 (sensor.lidar.ray_cast) 
paf22-test-agent-1            | ERROR: failed to destroy actor 7732 : unable to destroy actor: not found 
paf22-test-agent-1            | WARNING: attempting to unsubscribe from stream but sensor wasn't listening: Actor 7731 (sensor.camera.rgb) 
paf22-test-agent-1            | ERROR: failed to destroy actor 7731 : unable to destroy actor: not found 
paf22-test-agent-1            | WARNING: attempting to unsubscribe from stream but sensor wasn't listening: Actor 7730 (sensor.camera.rgb) 
paf22-test-agent-1            | ERROR: failed to destroy actor 7730 : unable to destroy actor: not found 
paf22-test-agent-1            | WARNING: attempting to unsubscribe from stream but sensor wasn't listening: Actor 7729 (sensor.camera.rgb) 
paf22-test-agent-1            | ERROR: failed to destroy actor 7729 : unable to destroy actor: not found 
paf22-test-agent-1            | WARNING: attempting to unsubscribe from stream but sensor wasn't listening: Actor 7728 (sensor.camera.rgb) 
paf22-test-agent-1            | ERROR: failed to destroy actor 7728 : unable to destroy actor: not found 
Aborting on container exit...
paf22-test-agent-1 exited with code 255
 Container paf22-test-agent-1  Stopping
 Container paf22-test-agent-1  Stopped
 Container paf22-test-roscore-1  Stopping
 Container paf22-test-carla-simulator-1  Stopping
 Container paf22-test-carla-simulator-1  Stopped
 Container paf22-test-roscore-1  Stopped
Error: Process completed with exit code 255.
```

**Comment by ll7** [comment]
https://github.com/una-auxme/paf23/actions/runs/8185238686/job/22381819489#step:6:11353

**Comment by ll7** [comment]
`RuntimeError: time-out of 300000ms while waiting for the simulator, make sure the simulator is ready and connected to carla-simulator:2000`

**Comment by ll7** [comment]
Re-run was successful.
https://github.com/una-auxme/paf23/pull/198/checks
